name: mp_text
description: Cross-platform MediaPipe text tasks for Dart and Flutter.
version: 0.0.0
repository: https://github.com/ifiokjr/mediapipe/tree/main/packages/mp_text
issue_tracker: https://github.com/ifiokjr/mediapipe/issues
homepage: https://ifiokjr.github.io/mediapipe/packages/text/
topics:
  - mediapipe
  - natural-language-processing
  - machine-learning
  - flutter

environment:
  sdk: ^3.12.0
  flutter: ">=3.44.0"

resolution: workspace

dependencies:
  collection: ^1.19.1
  flutter:
    sdk: flutter
  meta: ^1.17.0
  mp_core: ^0.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^6.0.0
  test: ^1.26.3

flutter:
  plugin:
    platforms:
      android:
        package: dev.ifiokjr.mptext
        pluginClass: MpTextPlugin
      ios:
        pluginClass: MpTextPlugin
